name: Pack File
run-name: Packing
on:
  push:
    branches:
      - 'main'
      - 'release/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Asset Packer
        uses: KrashV/starbound-asset-packer-action@v1
        with:
          input: .
          config: .github/tools/packing.config
          output: project-45.pak